[package]
name = "hurdle-controller-qt"
version = "0.1.0"
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
edition = "2018"

[dependencies]
clap = "3.2.6"

[dependencies.clippy]
version = "0.0.302"
optional = true

[features]
default = []
